### ISSUE TITLE
When  Place Markers add-on is updated saved place markers and searches are lost.

### ISSUE THREAD

**Issue by lukaszgo1** [nvdaes/placeMarkers#16]
## STR:
1. Install add-on updater.
2. install slightly older version of Place Markers, or modify manifest of the current version to give it lover version number.
3. Save some place markers for  web pages.
4. Check for add-on updates with add-on updater, and when update for the place marker is found agree to updating it.
### Expected
After update my place markers should remain in place.
### actual.
Place markers and saved searches are lost when updating.

**Comment by nvdaes** [comment]
Hi, this is expected since placeMarkers are saved in the own add-on, which is replaced when it's updated. Before updating the add-on, we need to go to NVDA's menu, Preferences, placeMarkers, and use the option to copy the placeMarkers folder.
This is done like that to avoid that, when uninstalling the add-on, non desired folders are stored in the user configuration folder, ensuring that the add-on doesn't copy things to this folder if the user hasn't chosen to do it.
Do you think it would be better to store bookmarks in the configuration folder, so that saving a copy is not needed?

**Comment by lukaszgo1** [comment]
I'm very sorry for the late reply - I've missed the notification. In my view when installation process starts place markers should be copied to the main folder and then copied back. It seems to be doable I'll probably look into this. The current behavior isn't very beginner friendly.

**Comment by nvdaes** [comment]
Hello, thanks for your comments.
This may be done storing placeMarkers directly on the main folder (in the user configuration directory). I didn't follow this approach to avoid that, when the add-on is uninstalled, if the user don't want to use it, placeMarkers remain in the user configuration folder. NVDA doesn't accept question when add-ons are uninstalled, so we can't ask if configuration files should be removed.
Anyway, please let me know if you still think that it would be better to store files in the main folder, after knowing my reasons.
Have a good day!

**Comment by lukaszgo1** [comment]
Hi @nvdaes 
I've created https://github.com/nvdaes/placeMarkers/pull/18
In my view this solution gives us the best of both words i.e. the main config folder isn't cluttered,  and data is retained during upgrades.
