### ISSUE TITLE
enable placemarkers in browse mode (like headings, links, buttons etc)

### ISSUE THREAD

**Issue by gregjozk** [nvdaes/placeMarkers#21]
Hello,

maybe a title does not describe correctly, what I mean.
When we are in browse mode, we can navigate between headings, links and other elements with single key or with shift plus single key, if we wanted to go to previous element. Is it possible, that placemarkers could be used in same way than other elements within browse mode?
If you want to use placemarker now, you must press NVDA key and key, which was provided in input gestures dialog.

thanks.
regards, Jožef

**Comment by nvdaes** [comment]
Sorry, I'm seeing this just now. In fact, you can assign a single letter like z in the input gestures dialog to go to the next bookmark, for example.
Please excuse me for my delay, and feel free to reopen this issue if you feel it's not fixed.
Many thanks for your interest

**Comment by gregjozk** [comment]
Hi,

no problem. when I tried your solution, (to use input gesture dialog), the placemarker (bookmark function) blocked chosen letter. it means, that I could not have to use chosen letter in regular usage e.g. could not have to write (z) or other chosen letter in focus mode. so if you don't mind, I would reopen this issue. hope, that I was clearer.
anyway, many thanks for your good work.

**Comment by nvdaes** [comment]
Thanks. I will get a look.

Enviado desde mi iPhone

**Comment by nvdaes** [comment]
Hello, I'm trying this following these steps. Please use the latest stable version of the add-on (14.0) or 15.1-dev.

1. Go to Input gestures dialog of NVDA.
2. Add z to move to the next bookmark.
3. Open a webpage like Google.
4. Press z in browse mode. Then the cursor moves to the next bookmark.
5. Activates focus mode to type in the search edit box.
6. Press z. Then z is writen.
 

I think this is the expected behavior. If this doesn't work for you, can you test this disabling other add-ons?

Thanks.
